name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Test
      run: go test -v ./...

    - name: Go coverage report
      uses: ncruces/go-coverage-report@v0.1.7
      with:
        report: 'true'
        chart: 'true'
        amend: 'false'
      if: |
        matrix.os == 'ubuntu-latest' &&
        github.event_name == 'push'  
      continue-on-error: true