name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Go coverage report
      uses: ncruces/go-coverage-report@v0
      with:
        report: 'true'
        chart: 'true'